# https://www.freecodecamp.org/news/publishing-github-event-data-with-github-actions-and-pages/
# https://stackoverflow.com/questions/58597010/how-to-access-a-github-issue-comment-body-using-github-actions
# This is a basic workflow to help you get started with Actions
# https://github.com/maguowei/iaas/blob/d48834c18b66ae0f3ae32e5e62a6811dfddadcb2/.github/workflows/iaas.yml
# replace invalid characters in filename https://stackoverflow.com/a/50876753/1553656

name: backup_images
description: "Backup images in markdown"
branding:
  icon: "archive"
  color: "green"
inputs:
  branch:
    description: "Target branch name to push the markdownfile"
    required: true
    default: "main"
  dir:
    description: "the posts dir"
    required: true
    default: "_posts"
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  actor:
    description: "github.actor"
    required: true
runs:
  using: composite
  steps:
    - name: Install Pandoc
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y pandoc
        mkdir -p "${{ inputs.dir }}/bk/media"
        mkdir -p media
        ls "${{ inputs.dir }}/*.md" | xargs -i sh -c 'cat {} | pandoc -f gfm --extract-media=media -o "${{ inputs.dir }}/bk/{}" -w gfm'
    - name: Push changes to repo
      shell: bash
      run: |
        cp media/* "${{ inputs.dir }}/bk/media/"
        REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config user.email "${{ inputs.actor }}@users.noreply.github.com"
        git config user.name "${{ inputs.actor }}"
        git pull ${REMOTE}
        git checkout ${{ inputs.branch }}
        git add "${{ inputs.dir }}"
        git status
        git commit -am "Add new comment"
        git push ${REMOTE} ${{ inputs.branch }}
